# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WirebondRecorderGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WirebondRecorder(object):
    def setupUi(self, WirebondRecorder):
        WirebondRecorder.setObjectName("WirebondRecorder")
        WirebondRecorder.resize(1060, 788)
        self.centralwidget = QtWidgets.QWidget(WirebondRecorder)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.sldrZoom = QtWidgets.QSlider(self.centralwidget)
        self.sldrZoom.setMinimum(0)
        self.sldrZoom.setMaximum(10)
        self.sldrZoom.setPageStep(1)
        self.sldrZoom.setProperty("value", 1)
        self.sldrZoom.setSliderPosition(1)
        self.sldrZoom.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sldrZoom.setObjectName("sldrZoom")
        self.verticalLayout.addWidget(self.sldrZoom)
        self.lblZoom = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblZoom.sizePolicy().hasHeightForWidth())
        self.lblZoom.setSizePolicy(sizePolicy)
        self.lblZoom.setMinimumSize(QtCore.QSize(30, 0))
        self.lblZoom.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lblZoom.setObjectName("lblZoom")
        self.verticalLayout.addWidget(self.lblZoom, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 4, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnChangeMode = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnChangeMode.sizePolicy().hasHeightForWidth())
        self.btnChangeMode.setSizePolicy(sizePolicy)
        self.btnChangeMode.setMinimumSize(QtCore.QSize(100, 40))
        self.btnChangeMode.setMaximumSize(QtCore.QSize(100, 40))
        self.btnChangeMode.setIconSize(QtCore.QSize(16, 16))
        self.btnChangeMode.setObjectName("btnChangeMode")
        self.horizontalLayout.addWidget(self.btnChangeMode)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.logText = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logText.sizePolicy().hasHeightForWidth())
        self.logText.setSizePolicy(sizePolicy)
        self.logText.setMinimumSize(QtCore.QSize(350, 75))
        self.logText.setMaximumSize(QtCore.QSize(350, 75))
        self.logText.setObjectName("logText")
        self.horizontalLayout.addWidget(self.logText)
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        self.btnSave.setMinimumSize(QtCore.QSize(90, 40))
        self.btnSave.setMaximumSize(QtCore.QSize(90, 40))
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblmainTitle = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblmainTitle.sizePolicy().hasHeightForWidth())
        self.lblmainTitle.setSizePolicy(sizePolicy)
        self.lblmainTitle.setMinimumSize(QtCore.QSize(340, 40))
        self.lblmainTitle.setMaximumSize(QtCore.QSize(340, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblmainTitle.setFont(font)
        self.lblmainTitle.setObjectName("lblmainTitle")
        self.horizontalLayout_2.addWidget(self.lblmainTitle)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBack.sizePolicy().hasHeightForWidth())
        self.btnBack.setSizePolicy(sizePolicy)
        self.btnBack.setMinimumSize(QtCore.QSize(90, 40))
        self.btnBack.setMaximumSize(QtCore.QSize(90, 40))
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout_2.addWidget(self.btnBack)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.imgSelect = QtWidgets.QGraphicsView(self.centralwidget)
        self.imgSelect.setObjectName("imgSelect")
        self.gridLayout.addWidget(self.imgSelect, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        WirebondRecorder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WirebondRecorder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        WirebondRecorder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WirebondRecorder)
        self.statusbar.setObjectName("statusbar")
        WirebondRecorder.setStatusBar(self.statusbar)
        self.actionSave_Ctrl_S = QtWidgets.QAction(WirebondRecorder)
        self.actionSave_Ctrl_S.setObjectName("actionSave_Ctrl_S")
        self.actionExit = QtWidgets.QAction(WirebondRecorder)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen_Ctrl_o = QtWidgets.QAction(WirebondRecorder)
        self.actionOpen_Ctrl_o.setObjectName("actionOpen_Ctrl_o")
        self.actionSave_As_Ctrl_a = QtWidgets.QAction(WirebondRecorder)
        self.actionSave_As_Ctrl_a.setObjectName("actionSave_As_Ctrl_a")
        self.actionOne_day = QtWidgets.QAction(WirebondRecorder)
        self.actionOne_day.setObjectName("actionOne_day")
        self.actionUploader_etc = QtWidgets.QAction(WirebondRecorder)
        self.actionUploader_etc.setObjectName("actionUploader_etc")
        self.actionAbout = QtWidgets.QAction(WirebondRecorder)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen_Ctrl_o)
        self.menuFile.addAction(self.actionSave_Ctrl_S)
        self.menuFile.addAction(self.actionSave_As_Ctrl_a)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionUploader_etc)
        self.menuHelp.addAction(self.actionOne_day)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(WirebondRecorder)
        QtCore.QMetaObject.connectSlotsByName(WirebondRecorder)

    def retranslateUi(self, WirebondRecorder):
        _translate = QtCore.QCoreApplication.translate
        WirebondRecorder.setWindowTitle(_translate("WirebondRecorder", "ITk Tracking GUI"))
        self.lblZoom.setText(_translate("WirebondRecorder", "1.0x"))
        self.btnChangeMode.setText(_translate("WirebondRecorder", "Edit"))
        self.btnSave.setText(_translate("WirebondRecorder", "Save"))
        self.lblmainTitle.setText(_translate("WirebondRecorder", "Wirebond Recorder"))
        self.btnBack.setText(_translate("WirebondRecorder", "Back"))
        self.menuFile.setTitle(_translate("WirebondRecorder", "File"))
        self.menuTools.setTitle(_translate("WirebondRecorder", "Tools"))
        self.menuHelp.setTitle(_translate("WirebondRecorder", "Help"))
        self.actionSave_Ctrl_S.setText(_translate("WirebondRecorder", "Save (Ctrl-S)"))
        self.actionExit.setText(_translate("WirebondRecorder", "Exit"))
        self.actionOpen_Ctrl_o.setText(_translate("WirebondRecorder", "Open (Ctrl-O)"))
        self.actionSave_As_Ctrl_a.setText(_translate("WirebondRecorder", "Save As (Ctrl-A)"))
        self.actionOne_day.setText(_translate("WirebondRecorder", "One day.."))
        self.actionUploader_etc.setText(_translate("WirebondRecorder", "Uploader, etc"))
        self.actionAbout.setText(_translate("WirebondRecorder", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WirebondRecorder = QtWidgets.QMainWindow()
    ui = Ui_WirebondRecorder()
    ui.setupUi(WirebondRecorder)
    WirebondRecorder.show()
    sys.exit(app.exec_())

